# Generated by Django 3.2.3 on 2021-05-20 02:00

import backend.sorteo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_alter_user_date_verify'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.sorteo.models.UserObjectManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lottery', to=settings.AUTH_USER_MODEL, verbose_name='lotteries')),
            ],
            options={
                'verbose_name': 'lottery',
                'verbose_name_plural': 'lotteries',
            },
        ),
    ]
